imports:
    - { resource: tables.yml }

services:
    danieltj.api.controller.api:
        class: danieltj\api\controller\api
        arguments:
            - '@auth'
            - '@request'
            - '@template'
            - '@language'
            - '@user'
            - '@danieltj.api.includes.functions'

    danieltj.api.controller.ucp:
        class: danieltj\api\controller\ucp
        arguments:
            - '@service_container'
            - '@dispatcher'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@danieltj.api.includes.functions'

    danieltj.api.listener:
        class: danieltj\api\event\listener
        arguments:
            - '@auth'
            - '@request'
            - '@template'
            - '@language'
            - '@user'
            - '@danieltj.api.includes.functions'
        tags:
            - { name: event.listener }

    danieltj.api.includes.functions:
        class: danieltj\api\includes\functions
        arguments:
            - '@auth'
            - '@dbal.conn'